### ISSUE TITLE
v2.0 Roadmap

### ISSUE THREAD

**Issue by localjo** [localjo/quotable-wp#5]
This is the roadmap for version 2.0:

- [x] Better code organization that follows the WordPress guidelines
- [x] Extract front end functionality to separate JS module that can be installed in other projects
- [x] Remove call to platform.twitter.com
- [x] Add support for Gutenberg block editor
  - [x] Migrate metabox to Gutenberg document settings sidebar
  - [x] Add block variation to enable/disable quotes
- [x] Hide quotable post/page settings if disabled on site
- [x] Internationalize all strings and add Spanish translation
- [x] Add what's new / support message on install/update
- [x] Add settings shortcut in plugin list
- [x] Make JavaScript settings extensible
- [ ] ~~Add survey request on uninstall (?)~~
- [ ] ~~Add support for `twitter://` protocol (?)~~
- [x] Test citation behavior
- [x] Test fresh install
- [x] Test multisite
- [x] Improve copy and styles on all UI elements
- [x] Test with older versions of WordPress
- [x] Update screenshots, social media images, and meta
- [x] Double check code standards and guidelines

**Comment by localjo** [comment]
For blocks, see if I can add a property to existing quote blocks to enable/disable the icon. It could be true/false/null and I could use it to add classes the to HTML output that could be used to include/exclude it from the JS config. Also, add styles to block editor.

**Comment by localjo** [comment]
In assets directory of SVN repo:

Banner: banner-772x250.png, banner-1544x500.png
Icon: icon-128x128.png, icon-256x256.png, icon.svg
Screenshots: screenshot-1.png, etc

https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

**Comment by localjo** [comment]
v2.0.0 has been published https://wordpress.org/plugins/quotable/
